---
- hosts: fwac
  tasks:
  - shell: hostname
    register: host
    when: myhost is not defined
  - debug:
      var: host
      verbosity: 2
  - local_action: shell hostname
    register: host
    when: myhost is not defined
  - debug:
      var: host
      verbosity: 2
  - local_action: shell hostname -i
    register: ip
    when: myip is not defined
  - debug:
      var: ip
      verbosity: 2

- hosts: labs
  tasks:
  - template:
      src: correcthorsebatterystaple.j2
      dest: /etc/changeme.conf
    tags:
      - j2
  - lineinfile:
      path: /etc/hosts
      regexp: "^{{ myip|default(ip.stdout) }}"
      line: "{{ myip|default(ip.stdout) }}      {{ myhost|default(host.stdout) }}"
      state: present
