---
- hosts: awx
  vars:
    filename: /tmp/scott.pptx
  connection: local
  tasks:
  - name: Create PPTX with Title page
    pptx_create: 
      filename: "{{ filename }}"
      title: "Ansible Club"
      subtitle: "This is what you want to do"

  - name: Create Bar Charts
    pptx_chart:
      filename: "{{ filename }}"
      categories: ['Yes',No']
      series_name: "Use Ansible"
      series_values: [5,10]
      chart_type: bar

  - name: Create Pie Charts
    pptx_chart:
      filename: "{{ filename }}"
      categories: ['Yes',No']
      series_name: "Use Ansible"
      series_values: [5,10]
      chart_type: pie

  - name: Transfer file to Google Drive
    local_action: "command gdrive upload --parent 1Ua_JEkk2GQh8KyiYchwpJWe5Bcob9T_E --mime application/vnd.openxmlformats-officedocument.presentationml.presentation --delete {{ filename }}"


