---
- hosts: awx
  vars:
    filename: /tmp/fwac.pptx
  tasks:
  - name: RESTHeart for collections
    uri:
      url: "http://{{restheart}}/db/{{ collection }}"
      return_content: yes
    register: coll

  - set_fact:
        currently: "{{ currently|default(0)|int + item.currently|bool|int }}"
        inops: "{{ inops|default(0)|int + item.inops|bool|int }}"
        challenge_cloud: "{{ challenge_cloud|default('') }} {{ item.challenge_cloud }}"
        club: "{{ club|default([]) + item.club }}"
        facilitate: "{{ facilitate|default('') }} {{ item.facilitate }}"
        meetings: "{{ meetings|default('') }} {{ item.meetings }}"
        reason_cloud: "{{ reason_cloud|default('') }} {{ item.reason_cloud  }}"
        role: "{{ role|default('') }} {{ item.role }}"
        topic: "{{ topic|default('') }} {{ item.topic }}"
        tower: "{{ tower|default([]) + item.tower }}"
    with_items: "{{coll.json._embedded}}"

  - debug: var=currently
    verbosity: 2
  - debug: var=inops
    verbosity: 2
  - debug: var=challenge_cloud
    verbosity: 2
  - debug: var=club
    verbosity: 2
  - debug: var=facilitate
    verbosity: 2
  - debug: var=meetings
    verbosity: 2
  - debug: var=reason_cloud
    verbosity: 2
  - debug: var=role
    verbosity: 2
  - debug: var=topic
    verbosity: 2
  - debug: var=tower
    verbosity: 2

  - name: Create PPTX with Title page
    pptx_create: 
      filename: "{{ filename }}"
      title: "Ansible Club"
      subtitle: "This is what you want to do"

  - name: Create Bar Charts
    pptx_chart:
      filename: "{{ filename }}"
      categories: ['Yes','No']
      series_name: "Use Ansible"
      series_values: [5,10]
      chart_type: bar

  - name: Create Pie Charts
    pptx_chart:
      filename: "{{ filename }}"
      categories: ['Yes','No']
      series_name: "Use Ansible"
      series_values: [5,10]
      chart_type: pie

  - name: Transfer file to Google Drive
    command: "aws s3 cp {{ filename }} s3://s3.fwac.us/slides/ --acl public-read"
    become: no


#local_action: "command gdrive upload --parent 1Ua_JEkk2GQh8KyiYchwpJWe5Bcob9T_E --mime application/vnd.openxmlformats-officedocument.presentationml.presentation --delete {{ filename }}"
