---
- hosts: awx
  vars:
    pptx_template: "/tmp/Presentation.pptx"
    reason_image_file: "/tmp/reason_cloud.png"
    challenge_image_file: "/tmp/challenge_cloud.png"
    why_image_file: "/tmp/why_cloud.png"

  tasks:
  - name: RESTHeart for collections
    uri:
      url: "http://{{restheart}}/{{ db }}/{{ collection }}"
      return_content: yes
    register: documents

  - name: RESTHeart for mail
    uri:
      url: "http://{{restheart}}/{{ db }}/mail/{{ email_from }}"
      return_content: yes
    register: email_col
    when: "email_from is defined"
        
  # set variables with all the answers together. the code in the module will
  # tally the answers to create the charts. Needs to provide a list
  - set_fact:
      currently_yes: "{{ currently_yes|default('0')|int + item.currently_ss|bool|int }}" #
      currently: "{{ currently|default([]) + [item.currently_ss] }}" #
      inops_yes: "{{ inops_yes|default('0')|int + item.inops_ss|bool|int }}" #
      inops: "{{ inops|default([]) + [item.inops_ss] }}" #
      challenge_cloud: "{{ challenge_cloud|default('') }} {{ item.challenge_cloud_text }}" #
      why_cloud: "{{ why_cloud|default('') }} {{ item.why_text }}" #      
      club: "{{ club|default([]) + item.club_ms }}" #
      emails: "{{ emails|default([]) + [item._id] }}"
      meetings: "{{ meetings|default([]) + [item.meetings_ss] }}" #
      project: "{{ project|default([]) + [item.project_text|upper] }}"
      reason_cloud: "{{ reason_cloud|default('') }} {{ item.reason_cloud_text  }}" #
      role: "{{ role|default([]) + [item.role_ss] }}" #
      topic: "{{ topic|default([]) + [item.topic_text] }}"
      name: "{{ name|default([]) + [item.name_text|default('None')] }}"
      table_data: "{{ table_data|default([]) + [[item.name_text|default('None'),item.project_text|default('None'),item.role_ss|default('None'),item.tower_ms|join(',')|default('None'),item._id|default('None')]]}}" 
      tower: "{{ tower|default([]) + item.tower_ms }}" #
      total: "{{ total|default(0)|int + 1|int }}"
    with_items: "{{documents.json._embedded}}"
    
  - debug: 
      var: currently
      verbosity: 2
  - debug: 
      var: inops
      verbosity: 2
  - debug: 
      var: challenge_cloud
      verbosity: 2
  - debug: 
      var: club
      verbosity: 2
  - debug: 
      var: emails
      verbosity: 2
  - debug: 
      var: meetings
      verbosity: 2
  - debug: 
      var: reason_cloud
      verbosity: 2
  - debug: 
      var: role
      verbosity: 2
  - debug: 
      var: topic
      verbosity: 2
  - debug: 
      var: tower
      verbosity: 2
  - debug:
      var: table_data
      verbosity: 2
  - debug: 
      var: total
      verbosity: 2
 
  - name: Copy PPTX template
    copy: 
      src: "{{ pptx_template|basename }}"
      dest: "{{ pptx_template }}"
    
  - name: Create PPTX with Title page
    pptx_create: 
      template: "{{ pptx_template }}"
      filename: "{{ pptx_filename }}"
      title: "Ansible Club"
      subtitle: "This is what you want to do"

  # silos 
  - name: Clean artifact path
    file:
      state: absent
      path: /tmp/silo/
  
  - name: Creates directory for silos
    file: 
      path: /tmp/silo 
      state: directory
  
  - name: Copy Sideways Image
    copy: 
      src: "silo.png"
      dest: "/tmp/sideways_silo.png"      

  - name: Building Silos
    command: "convert /tmp/sideways_silo.png -gravity Center -fill white -size 200x20 -pointsize 26 -annotate +0-10 '{{ item }}' -rotate 90  /tmp/silo/temp{{ idx }}.png"
    loop: "{{ project|unique }}"
    loop_control:
      index_var: idx
    when: "idx < 22"
       
  - name: Silo Montage
    raw: "montage /tmp/silo/temp{{'{0..' ~ (project|unique|length|int - 1) ~ '}'}}.png -resize 60% -background none -tile 7x3 -geometry +0+0 /tmp/silo/out.png"
     
  - name: Add Silos to PPTX
    pptx_image:
      image: "/tmp/silo/out.png"
      title: "How we currently work"
      filename: "{{ pptx_filename }}"
      top_inches: 1.7
      left_inches: 0.7
      
  - name: Pie chart of why we clubbing
    pptx_chart:
      title: "What we want from Ansible Club"
      filename: "{{ pptx_filename }}"
      categories: "{{ club|unique|list }}"
      series_values: "{{ club }}"
      series_name: 
       - "Reasons we are here"
      chart_type: "pie"

  - name: Who we are 
    pptx_chart:
      title: "Who we are..."
      filename: "{{ pptx_filename }}"
      categories: "{{ role|unique|list }}"
      series_values: "{{ role }}"
      series_name: 
       - "Who we are"
      chart_type: "pie"
     
  - name: Are we using Ansible Bar Chart
    pptx_chart:
      title: "Where do you use Ansible?"
      filename: "{{ pptx_filename }}"
      series_build: False
      categories: ['Development','Operations'] 
      series_name: ['Yes','No']
      series_values: 
        - ['{{ currently_yes|int }}','{{ inops_yes|int }}']
        - ['{{ total|int - currently_yes|int }}','{{ total|int - inops_yes|int }}']
      chart_type: "bar"

  - name: Pie chart of DevOps
    pptx_chart:
      title: "Just Dev or DevOps"
      filename: "{{ pptx_filename }}"
      categories: ['Just Dev','DevOps']
      series_values: ['{{ currently_yes|int - inops_yes|int }}','{{ inops_yes }}']
      series_build: False
      series_name: 
       - "Just Dev or DevOps"
      chart_type: "pie"
      
  - name: Who uses Tower vs Engine
    pptx_chart:
      title: "How we use Ansible"
      filename: "{{ pptx_filename }}"
      categories: "{{ tower|unique|list }}"
      series_name: 
       - "Tower vs Engine"
      series_values: "{{ tower }}"
      chart_type: "bar"
      
  - name: How ofter we meet
    pptx_chart:
      title: "How often we want to meet"
      filename: "{{ pptx_filename }}"
      categories: "{{ meetings|unique|list }}"
      series_name: 
       - "Meeting interval"
      series_values: "{{ meetings }}"
      chart_type: "bar"

     
  # reason cloud ===================================================     
  - name: Create reason cloud
    word_cloud:
      image_file: "{{ reason_image_file }}"
      words: "{{ reason_cloud }}"
      colormap: 'autumn'
      mode: 'RGBA'
  
  - name: Add reason_cloud to pptx
    pptx_image:
      title: "Why we love Ansible"
      image: "{{ reason_image_file }}"
      filename: "{{ pptx_filename }}"
      
  #challenge cloud =================================================

  - name: Create Challenge Cloud
    word_cloud:
      image_file: "{{ challenge_image_file }}"
      words: "{{ challenge_cloud }}"
      colormap: 'summer'
      mode: 'RGBA'      
     
  - name: Add challenge_cloud to pptx
    pptx_image:
      title: "DevOps Challenges"
      image: "{{ challenge_image_file }}"
      filename: "{{ pptx_filename }}"

  #why cloud =================================================

  - name: Create why cloud
    word_cloud:
      image_file: "{{ why_image_file }}"
      words: "{{ why_cloud }}"
      colormap: 'Wistia'
      mode: 'RGBA'      
     
  - name: Add why_cloud to pptx
    pptx_image:
      title: "Polices and Procedures"
      image: "{{ why_image_file }}"
      filename: "{{ pptx_filename }}"      

 # add topics   
  - name: Topics for discussion
    pptx_bullet:
      title: "Discussion"
      filename: "{{ pptx_filename }}"
      bullets: "{{ topic }}"
      count: 5
    when: "topic|length > 0"


  # put it all up on S3    
  - name: Put slides up on S3
    aws_s3:
      bucket: s3.fwac.us
      object: "/slides/{{ pptx_filename | basename }}"
      src: "{{ pptx_filename }}"
      mode: put
      permission: public-read

  - name: Make index.html for S3 
    template:
        src: index.html.j2
        dest: /tmp/index.html
    register: index_html

  - name: Put index up on S3
    aws_s3:
      bucket: s3.fwac.us
      object: "/index.html"
      src: "/tmp/index.html"
      mode: "put"
      permission: public-read  
    when: index_html is changed

  - name: Update fwac.github.io
    git:
      repo: git@github.com:fwac/fwac.github.io.git
      dest: /home/ec2-user/fwac.github.io
      update: yes
      force: yes
      version: master 

  - name: Get list off slides from s3
    aws_s3:
      bucket: s3.fwac.us
      prefix: slides/
      mode: list
    register: slides
    
  - name: Update README 
    template:
        src: README.md.j2
        dest: /home/ec2-user/fwac.github.io/README.md
        
  - name: Push README
    shell: "cd /home/ec2-user/fwac.github.io && /home/ec2-user/bin/push"  
    
  - name: Add Attendance table to pptx for email only
    pptx_table:
      title: "Attendance"
      filename: "{{ pptx_filename }}"
      table_data: "{{ table_data }}"

  - name: Email Slides to attendees
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ email_from }}"
      password: "{{ email_col.json.passwd }}"
      to: "{{ emails }}"
      subject: FWAC Meeting Slides
      from: scott.ctr.tully@gmail.com
      body: "Ansible has created a PowerPoint Presentation for you. The slides are attached.\n\nPlaybooks and source code available here https://github.com/fwac/fwac\n\nEnjoy!"
      attach:
        - "{{ pptx_filename }}"
      headers:
        - Reply-To=scott.ctr.tully@faa.gov
    when: "email_col.json is defined and email_from is defined"
 
