---
- hosts: awx
  vars:
    filename: /tmp/fwac.pptx
  tasks:
  - name: RESTHeart for collections
    uri:
      url: "http://{{restheart}}/db/{{ collection }}"
      return_content: yes
    register: coll

  # set variables with all the answers together. the code in the module will
  # tally the answers to create the charts
  - set_fact:
        currently_yes: "{{ currently|default(0)|int + item.currently|bool|int }}"
	inops_yes: "{{ inops|default(0)|int + item.inops|bool|int }}"
        currently: "{{ currently|default('') }} {{ item.currently }}"
        inops: "{{ inops|default('') }} {{ item.inops }}"
        challenge_cloud: "{{ challenge_cloud|default('') }} {{ item.challenge_cloud }}"
        club: "{{ club|default([]) + item.club }}"
        facilitate: "{{ facilitate|default('') }} {{ item.facilitate }}"
        meetings: "{{ meetings|default('') }} {{ item.meetings }}"
        reason_cloud: "{{ reason_cloud|default('') }} {{ item.reason_cloud  }}"
        role: "{{ role|default('') }} {{ item.role }}"
        topic: "{{ topic|default('') }} {{ item.topic }}"
        tower: "{{ tower|default([]) + item.tower }}"
    with_items: "{{coll.json._embedded}}"

  - debug: var=currently
    verbosity: 2
  - debug: var=inops
    verbosity: 2
  - debug: var=challenge_cloud
    verbosity: 2
  - debug: var=club
    verbosity: 2
  - debug: var=facilitate
    verbosity: 2
  - debug: var=meetings
    verbosity: 2
  - debug: var=reason_cloud
    verbosity: 2
  - debug: var=role
    verbosity: 2
  - debug: var=topic
    verbosity: 2
  - debug: var=tower
    verbosity: 2

  - name: Create PPTX with Title page
    pptx_create: 
      filename: "{{ filename }}"
      title: "Ansible Club"
      subtitle: "This is what you want to do"

  - name: Pie chart of why we clubbing
    pptx_chart:
      title: "What we want from Ansible Club"
      filename: "{{ filename }}"
      categories: ['Yes','No']
      series_dict: { total: '{{ currently_yes }}', part: '{{ inops_yes }}' }
      series_name: "Use Ansible"
      chart_type: "pie"



  - name: Who uses Ansible Bar Chart
    pptx_chart:
      title: "Who uses Ansible?"
      filename: "{{ filename }}"
      categories: ['Yes','No']
      series_name: "Use Ansible"
      series_answers: "{{ currently }}"
      chart_type: "bar"

  - name: Who uses Ansible in Ops Bar Chart
    pptx_chart:
      title: "Who uses Ansible in Ops?"
      filename: "{{ filename }}"
      categories: ['Yes','No']
      series_name: "Use Ansible"
      series_answers: "{{ inops }}"
      chart_type: "bar"

  - name: Pie chart of Ansible use
    pptx_chart:
      title: "Where Ansibe is used"
      filename: "{{ filename }}"
      categories: ['Yes','No']
      series_dict: { total: '{{ currently_yes }}', part: '{{ inops_yes }}' }
      series_name: "Use Ansible"
      chart_type: "pie"


  - name: Create Pie Charts
    pptx_chart:
      title: ""
      filename: "{{ filename }}"
      categories: ['Yes','No']
      series_name: "Use Ansible"
      series_values: [5,10]
      chart_type: pie

  - name: Transfer file to Google Drive
    command: "aws s3 cp {{ filename }} s3://s3.fwac.us/slides/ --acl public-read"
    become: no


#local_action: "command gdrive upload --parent 1Ua_JEkk2GQh8KyiYchwpJWe5Bcob9T_E --mime application/vnd.openxmlformats-officedocument.presentationml.presentation --delete {{ filename }}"
