---
- hosts: awx
  vars:
    pptx_filename: "/tmp/fwac.pptx"
    collection: coll3
    
    reason_image_file: "/tmp/reason_cloud.png"
    reason_mask_file: "/tmp/reason_mask.png"
    reason_negative_file: "/tmp/reason_mask.png"   
    reason_cloud_file: "/tmp/reasons.png"      
    reason_word_file: "/tmp/reason_word.txt"
    
    challenge_image_file: "/tmp/challenge_cloud.png"
    challenge_mask_file: "/tmp/challenge_mask.png" 
    challenge_cloud_file: "/tmp/challenges.png"  
    challenge_word_file: "/tmp/challenge_word.txt"
  tasks:
  - name: RESTHeart for collections
    uri:
      url: "http://{{restheart}}/db/{{ collection }}"
      return_content: yes
    register: documents

  # set variables with all the answers together. the code in the module will
  # tally the answers to create the charts. Needs to provide a list
  - set_fact:
      currently_yes: "{{ currently|default(0)|int + item.currently_ss|bool|int }}" #
      currently: "{{ currently|default([]) + [item.currently_ss] }}" #
      inops_yes: "{{ inops|default(0)|int + item.inops_ss|bool|int }}" #
      inops: "{{ inops|default([]) + [item.inops_ss] }}" #
      challenge_cloud: "{{ challenge_cloud|default('') }} {{ item.challenge_cloud_text }}" #
      club: "{{ club|default([]) + item.club_ms }}" #
      facilitate: "{{ facilitate|default([]) + [item.facilitate_ss] }}"
      facilitate_yes: "{{ facilitate|default(0)|int  + item.facilitate_ss|bool|int }}"
      meetings: "{{ meetings|default([]) + [item.meetings_ss] }}" #
      reason_cloud: "{{ reason_cloud|default('') }} {{ item.reason_cloud_text  }}" #
      role: "{{ role|default([]) + [item.role_ss] }}" #
      topic: "{{ topic|default([]) + [item.topic_text] }}"
      tower: "{{ tower|default([]) + item.tower_ms }}" #
      total: "{{ total|default('1')|int + '1'|int }}"
    with_items: "{{documents.json._embedded}}"
    
  - debug: var=currently
    verbosity: 2
  - debug: var=inops
    verbosity: 2
  - debug: var=challenge_cloud
    verbosity: 2
  - debug: var=club
    verbosity: 2
  - debug: var=facilitate
    verbosity: 2
  - debug: var=meetings
    verbosity: 2
  - debug: var=reason_cloud
    verbosity: 2
  - debug: var=role
    verbosity: 2
  - debug: var=topic
    verbosity: 2
  - debug: var=tower
    verbosity: 2
  - debug: var=total
    verbosity: 2
    
  - name: Create PPTX with Title page
    pptx_create: 
      filename: "{{ pptx_filename }}"
      title: "Ansible Club"
      subtitle: "This is what you want to do"

  - name: Pie chart of why we clubbing
    pptx_chart:
      title: "What we want from Ansible Club"
      filename: "{{ pptx_filename }}"
      categories: "{{ club|unique|list }}"
      series_values: "{{ club }}"
      series_name: "Reasons we are here"
      chart_type: "pie"

  - name: Who we are 
    pptx_chart:
      title: "Who we are"
      filename: "{{ pptx_filename }}"
      categories: "{{ role|unique|list }}"
      series_values: "{{ role }}"
      series_name: "Who we are"
      chart_type: "pie"
      
  - name: Who uses Ansible Bar Chart
    pptx_chart:
      title: "Who uses Ansible?"
      filename: "{{ pptx_filename }}"
      categories: "{{ currently|unique|list }}"
      series_name: "Use Ansible"
      series_values: "{{ currently }}"
      chart_type: "bar"

  - name: Who uses Ansible in Ops Bar Chart
    pptx_chart:
      title: "Who uses Ansible in Ops?"
      filename: "{{ pptx_filename }}"
      categories: "{{ inops|unique|list }}"
      series_name: "Use Ansible"
      series_values: "{{ inops }}"
      chart_type: "bar"

  - name: Pie chart of Ansible use
    pptx_chart:
      title: "How we use Ansible"
      filename: "{{ pptx_filename }}"
      categories: ['Total','Using Ansible','Ops']
      series_dict: { total: '{{ total }}', currently: '{{ currently_yes }}', part: '{{ inops_yes }}' }
      series_name: "Ansible Use"
      chart_type: "pie"
      
  - name: Who uses Tower vs Engine
    pptx_chart:
      title: "Breakdown of how we use Ansible"
      filename: "{{ pptx_filename }}"
      categories: "{{ tower|unique|list }}"
      series_name: "Tower vs Engine"
      series_values: "{{ tower }}"
      chart_type: "bar"
      
  - name: How ofter we meet
    pptx_chart:
      title: "How often we want to meet"
      filename: "{{ pptx_filename }}"
      categories: "{{ meetings|unique|list }}"
      series_name: "Meeting interval"
      series_values: "{{ meetings }}"
      chart_type: "bar"

  - name: Copy cloud files to remote
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: '{{ reason_image_file|basename }}', dest: '{{ reason_image_file }}' }
      - { src: '{{ reason_mask_file|basename }}', dest: '{{ reason_mask_file }}' }
      - { src: '{{ challenge_image_file|basename }}', dest: '{{ challenge_image_file }}' }
      - { src: '{{ challenge_mask_file|basename }}', dest: '{{ challenge_mask_file }}' }      
      
  # reason cloud ===================================================     
  - name: Create word file for reason cloud
    copy:
      dest: "{{ reason_word_file }}"
      content:  "{{ reason_cloud }}"
      
  - name: Create reason cloud
    word_cloud:
      image_file: "{{ reason_image_file }}"
      mask_file: "{{ reason_mask_file }}"
      word_file: "{{ reason_word_file }}"    
      
  - name: Merge files with Magick
    command: "convert {{ reason_mask_file }} {{ reason_image_file }} {{ reason_negative_file }} -composite {{ reason_cloud_file }}"
      
  - name: Put reason_cloud up on S3
    aws_s3:
      bucket: s3.fwac.us
      object: /slides/{{ reason_cloud_file | basename }}
      src: {{ reason_cloud_file }}
      mode: put
      permission: public-read
      
  - name: Add reason_cloud to pptx
    pptx_image:
      title: "Why we love Ansible <3"
      filename: "{{ reason_cloud_file }}"
      
  #challenge cloud =================================================
  - name: Create word file for challenge cloud
    copy:
      dest: "{{ challenge_word_file }}"
      content:  "{{ challenge_cloud }}"
      
  - name: Create challenge cloud
    word_cloud:
      image_file: "{{ challenge_image_file }}"
      mask_file: "{{ challenge_mask_file }}"
      word_file: "{{ challenge_word_file }}"  
      
  - name: Put challenge_cloud up on S3
    aws_s3:
      bucket: s3.fwac.us
      object: /slides/{{ challenge_image_file| basename }}
      src: {{ challenge_image_file }}
      mode: put
      permission: public-read
      
  - name: Add challenge_cloud to pptx
    pptx_image:
      title: "Challenges we face"
      filename: "{{ challenge_image_file }}"
      
 # add topics   
  - name: Topics for discussion
    pptx_chart:
      title: "Discussion"
      filename: "{{ pptx_filename }}"
      bullets: "{{ topic }}"

  # put it all up on S3    
  - name: Put slides up on S3
    aws_s3:
      bucket: s3.fwac.us
      object: /slides/{{ pptx_filename | basename }}
      src: {{ pptx_filename }}
      mode: put
      permission: public-read

#local_action: "command gdrive upload --parent 1Ua_JEkk2GQh8KyiYchwpJWe5Bcob9T_E --mime application/vnd.openxmlformats-officedocument.presentationml.presentation --delete {{ filename }}"
