---
- hosts: awx
  vars:
    collection: meeting0
    survey: {    
      role_ss: 'Test Engineer',
      currently_ss: 'Yes',
      inops_ss: 'No',
      project_text: 'IAM',
      tower_ms: ['Engine'],
      club_ms: ['Learn','Have Fun/Socialize'],
      email_text: ['scott.tully@gmail.com'],
      meetings_ss: 'Bi-Monthly',
      reason_cloud_text: 'Automation Easy Idempotent Configuration Management Changes deployment integration devops CM',
      challenge_cloud_text: 'Policy Environments Ops Requirements SSM CM Test',
      topic_text: 'Show and tell'
      }

  tasks:
  - name: Put response in Mongo
    uri:
      url: "http://{{ restheart }}/db/{{ collection }}"
      body_format: "json"
      method: "POST"
      body: "{{survey}}"
      status_code: 201

  - name: Test Rest
    uri:
      url: "http://{{ restheart }}/db/{{ collection }}"
      return_content: yes
    register: coll

  - set_fact:
      currently_yes: "{{ currently|default(0)|int + item.currently_ss|bool|int }}"
      currently: "{{ currently|default([]) + [item.currently_ss] }}"
      inops_yes: "{{ inops|default(0)|int + item.inops_ss|bool|int }}"
      inops: "{{ inops|default([]) + [item.inops_ss] }}"
      challenge_cloud: "{{ challenge_cloud|default('') }} {{ item.challenge_cloud_text }}"
      club: "{{ club|default([]) + item.club_ms }}"
      emails: "{{ emails|default([]) + item.email_text }}"
      meetings: "{{ meetings|default([]) + [item.meetings_ss] }}"
      reason_cloud: "{{ reason_cloud|default('') }} {{ item.reason_cloud_text  }}"
      role: "{{ role|default([]) + [item.role_ss] }}"
      topic: "{{ topic|default([]) + [item.topic_text] }}"
      tower: "{{ tower|default([]) + item.tower_ms }}"
      total: "{{ total|default('1')|int + '1'|int }}"
    with_items: "{{coll.json._embedded}}"

  - set_fact:
      club_cat: "{{ club|unique }}"
       


  - debug: var=currently
  - debug: var=inops
  - debug: var=challenge_cloud
  - debug: var=club
  - debug: var=facilitate
  - debug: var=meetings
  - debug: var=tower

