---
- hosts: awx
  vars:
    fwac: { 
            challenge_cloud: '{{challenge_cloud}}', 
            club: '{{club}}', 
            currently: '{{currently}}', 
            facilitate: '{{facilitate}}', 
            inops: '{{inops}}', 
            meetings: '{{meetings}}', 
            reason_cloud: '{{reason_cloud}}', 
            role: '{{role}}', 
            topic: '{{topic}}', 
            tower: '{{tower}}' 
          }
    hard_fwac: { 
                 "challenge_cloud": "Policy Environments Ops Requirements SSM CM Test",
                 "club": ["Learn","Have Fun/Socialize","Read/Write/Run Playbooks","Demos/Workshops","Establish Playbook Standards"],
                 "currently": "Yes",
                 "facilitate": "Yes",
                 "inops": "Yes",
                 "meetings": "Weekly",
                 "reason_cloud": "Automation Easy Idempotent Configuration Management Changes deployment integration devops CM",
                 "role": "Developer/Engineer",
                 "topic": "none",
                 "tower": ["Tower","Engine"]
               }
  tasks:
  - name: Put response in Mongo
    uri:
      url: "http://172.31.16.159:8080/db/coll"
      body_format: "json"
      method: "POST"
      body: "{{hard_fwac}}"
      status_code: 201

  - name: Test Rest
    uri:
      url: http://172.31.16.159:8080/db/coll
      return_content: yes
    register: coll

  - set_fact:
        currently: "{{ currently|default(0)|int + item.currently|bool|int }}"
        inops: "{{ inops|default(0)|int + item.inops|bool|int }}"
        challenge_cloud: "{{ challenge_cloud }} {{ item.challenge_cloud }}"
        club: "{{ club|default([]) + item.club }}"
        facilitate: "{{ item.facilitate }}"
        meetings: "{{ meetings|default([]).append(item.meetings) }}"
        reason_cloud: "{{ reason_cloud }} {{ item.reason_cloud  }}"
        role: "{{ role|default([]).append(item.role) }}"
        topic: "{{ topic|default([]).append(item.topic) }}"
        tower: "{{ tower|default([]).apend(item.tower) }}"
    with_items: "{{coll.json._embedded}}"

  - debug: var=currently
  - debug: var=inops
  - debug: var=challenge_cloud
  - debug: var=club
  - debug: var=facilitate
  - debug: var=meetings
