---
- hosts: awx
  vars:
    collection: coll2
    fwac: { 
            challenge_cloud: '{{challenge_cloud}}', 
            club: '{{club}}', 
            currently: '{{currently}}', 
            facilitate: '{{facilitate}}', 
            inops: '{{inops}}', 
            meetings: '{{meetings}}', 
            reason_cloud: '{{reason_cloud}}', 
            role: '{{role}}', 
            topic: '{{topic}}', 
            tower: '{{tower}}' 
          }
    hard_fwac: { 
                 "challenge_cloud": "Policy Environments Ops Requirements SSM CM Test",
                 "club": ["Learn","Have Fun/Socialize","Read/Write/Run Playbooks","Demos/Workshops","Establish Playbook Standards"],
                 "currently": "Yes",
                 "facilitate": "Yes",
                 "inops": "No",
                 "meetings": "Weekly",
                 "reason_cloud": "Automation Easy Idempotent Configuration Management Changes deployment integration devops CM",
                 "role": "Developer/Engineer",
                 "topic": "none",
                 "tower": ["Tower","Engine"]
               }
  tasks:
  - name: Put response in Mongo
    uri:
      url: "http://{{ restheart }}/db/{{ collection }}"
      body_format: "json"
      method: "POST"
      body: "{{hard_fwac}}"
      status_code: 201

  - set_fact:
      currently: []

  - name: Test Rest
    uri:
      url: "http://{{ restheart }}/db/{{ collection }}"
      return_content: yes
    register: coll

  - set_fact:
      currently_yes: "{{ currently|default(0)|int + item.currently|bool|int }}"
      currently: "{{ currently + [item.currently] }}"
      inops_yes: "{{ inops|default(0)|int + item.inops|bool|int }}"
      inops: "{{ inops|default([]) + [item.inops] }}"
      challenge_cloud: "{{ challenge_cloud|default('') }} {{ item.challenge_cloud }}"
      club: "{{ club|default([]) + [item.club] }}"
      facilitate: "{{ facilitate|default([]) + [item.facilitate] }}"
      facilitate_yes: "{{ facilitate|default(0)|int  + item.facilitate|bool|int }}"
      meetings: "{{ meetings|default([]) + [item.meetings] }}"
      reason_cloud: "{{ reason_cloud|default('') }} {{ item.reason_cloud  }}"
      role: "{{ role|default([]) + [item.role] }}"
      topic: "{{ topic|default([]) + [item.topic] }}"
      tower: "{{ tower|default([]) + [item.tower] }}"
      total: "{{ total|default('1')|int + '1'|int }}"
    with_items: "{{coll.json._embedded}}"

  - set_fact:
      club_cat: "{{ club|unique }}"
       


  - debug: var=currently
  - debug: var=inops
  - debug: var=challenge_cloud
  - debug: var=club
  - debug: var=facilitate
  - debug: var=meetings
  - debug: var=tower

