---
- hosts: awx
  vars:
    # if not required provide default()
    survey: {
      role_ss: "{{ role_ss }}",
      currently_ss: "{{ currently_ss }}",
      inops_ss: "{{ inops_ss }}",
      project_text: "{{ project_text }}",
      tower_ms: "{{ tower_ms|default([]) }}",
      club_ms: "{{ club_ms }}",
      _id: "{{ email_text }}",
      meetings_ss: "{{ meetings_ss }}",
      reason_cloud_text: "{{ reason_cloud_text }}",
      challenge_cloud_text: "{{ challenge_cloud_text }}",
      topic_text: "{{ topic_text }}",
      name_text: "{{ name_text|default('') }}",
      why_text: "{{ why_text }}"
      }

  tasks:
  - name: RESTHeart PUT collection 
    uri:
      url: "http://{{restheart}}/db/{{ collection }}"
      method: PUT
      status_code: "201,200"

  - name: Put answers in Mongo
    uri:
      url: "http://{{ restheart }}/db/{{ collection }}"
      body_format: "json"
      method: "POST"
      body: "{{survey}}"
      status_code: 200,201

  - name: Email Notification
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ email_from }}"
      password: "{{ email_passwd }}"
      to: "scott.ctr.tully@faa.gov"
      subject: FWAC Survey Submitted
      from: scott.ctr.tully@gmail.com
      body: "{{ name_text }} ({{ email_text }}) submitted a survey\n\n {{survey|to_nice_yaml}}"
      headers:
        - Reply-To=scott.ctr.tully@faa.gov
    when: "email_passwd is defined"

