---
- hosts: localhost
  connection: local
  tasks:
  - name: install ca package on rhel systems
    yum:
      name: ca-certificates
      state: present

  - name: enable dynamic ca configuration on rhel6
    shell: /bin/update-ca-trust enable

  - name: copy certificate authority to trusted ca path of the os
    copy:
      src: /root/myCA.pem
      dest: /etc/pki/ca-trust/source/anchors/
      owner: root
      group: root
      mode: 0644
    notify:
      - update trusted ca redhat

  handlers:
  - name: update trusted ca redhat
    shell: /bin/update-ca-trust

